package enigma.engine;

public enum LoadXmlErrorType {
    NONE,
    INVALID_EXTENSION,
    INVALID_ABC_SIZE,
    DUPLICATE_ABC,
    NOT_ENOUGH_ROTORS,
    ROTOR_IDS_NOT_CONSECUTIVE,
    ROTOR_INVALID_NOTCH,
    ROTOR_MAPPING_NOT_FULL,
    ROTOR_MAPPING_INVALID_LETTER,
    ROTOR_DUPLICATE_MAPPING,
    NO_REFLECTORS,
    INVALID_REFLECTOR_ID,
    REFLECTOR_IDS_NOT_CONSECUTIVE,
    REFLECTOR_INVALID_LETTER,
    REFLECTOR_SELF_MAPPING,
    REFLECTOR_DUPLICATE_MAPPING,
    REFLECTOR_NOT_FULL_MAPPING,
    REFLECTOR_NOT_SYMMETRIC,
    ROTORS_COUNT_ZERO,
    TECHNICAL_ERROR
}