package enigma.engine;

public enum ManualCodeErrorType {
    NONE,
    ROTORS_COUNT_MISMATCH,
    ROTOR_ID_OUT_OF_RANGE,
    ROTOR_ID_DUPLICATE,
    WINDOW_LENGTH_MISMATCH,
    WINDOW_LETTER_NOT_IN_ABC,
    REFLECTOR_INDEX_OUT_OF_RANGE,
    PLUG_CHAR_NOT_IN_ABC,
    PLUG_SELF_MAPPING,
    PLUG_CHAR_DUPLICATE
}
