server.servlet.context-path=/enigma

spring.datasource.url=jdbc:postgresql://localhost:5432/enigma?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=enigma
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true